# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Customer

# Model Form Field configuration
form: $/bookrr/keeprr/models/customer/fields.yaml

# Model Class name
modelClass: Bookrr\Keeprr\Models\Customer

# Default redirect location
defaultRedirect: bookrr/keeprr/customer

# Create page
create:
    title: Create Customer
    redirect: bookrr/keeprr/customer/update/:id
    redirectClose: bookrr/keeprr/customer

# Update page
update:
    title: Edit Customer
    redirect: bookrr/keeprr/customer
    redirectClose: bookrr/keeprr/customer

# Preview page
preview:
    title: Preview Customer
